name: Sync Labels with Organization Standards

on:
  # Run manually when needed
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout organization .github repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/.github
          path: org-github

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install github-label-sync
        run: npm install -g github-label-sync

      - name: Sync labels from organization standards
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f "org-github/labels.yml" ]; then
            echo "Syncing labels to ${{ github.repository }}..."
            github-label-sync --access-token $GITHUB_TOKEN --labels org-github/labels.yml ${{ github.repository }}
          else
            echo "Error: labels.yml not found in organization .github repository"
            exit 1
          fi
